#!/bin/sh
set -e

case "$1" in
    configure)
        systemctl daemon-reload
        systemctl enable mediasmartserver
        systemctl start mediasmartserver
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
