#!/bin/sh
set -e

case "$1" in
    install|upgrade)
        if systemctl is-active --quiet mediasmartserver 2>/dev/null; then
            systemctl stop mediasmartserver
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
